sudo: required

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

language: java

jdk:
  - oraclejdk8

install: true # skip default travis build

before_script:
# install heroku stand alone cli to restart ct-payment-integration-java app
# this script requires sudo
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh

script:
  - /usr/local/heroku/bin/heroku restart --app ct-payment-integration-java # requires HEROKU_API_KEY env variable
  - set -e
  - ./gradlew --info build || travis_terminate 1
  - ./travis-build-publish.sh || travis_terminate 1

jdk:
  - oraclejdk8

notifications:
  email:
    on_success: change
    on_failure: change